name: Test

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix develop --command make
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
      - run: nix develop --command make test
